Int, Float, List, dict Mathimatical operations

In [12]:
[1, 2] * [1, 2]

TypeError: can't multiply sequence by non-int of type 'list'

In [15]:
a = [1, 2] 
b = a * 10
b

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [2]:
import numpy as np

a = np.array( [1, 2])

In [7]:
m = np.array( [ [1, 2], [3, 4] ])

In [11]:
m

array([[1, 2],
       [3, 4]])

In [10]:
m * m

array([[ 1,  4],
       [ 9, 16]])

In [3]:
a*10

array([10, 20])

In [4]:
import pandas as pd
df = pd.DataFrame( {"a": [1,2], "b": [3,4]})

In [5]:
df

a  b
0  1  3
1  2  4

In [6]:
df*10

a   b
0  10  30
1  20  40

In [39]:
a = [1,2]
b = [11,12, 13]
c = [1.1,2.0,3] 
(a + b)



[1, 2, 11, 12, 13]

(1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)

In [35]:
a*2

(1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10)

In [37]:
a + c

(1, 2, 1.1, 2.0, 3)

In [40]:
c*c

TypeError: can't multiply sequence by non-int of type 'list'

In [64]:
c
print("Loop - strated here")

for i in c:
    m = i*2
     
    print("L1 - ", i, m)
    
    break
    
print("Loop - ended here")
    
print("L0 - ", i, m)

Loop - strated here
L1 -  1.1 2.2
Loop - ended here
L0 -  1.1 2.2


In [51]:
c

[1.1, 2.0, 3]